### ISSUE TITLE
Main JS dependency is out of sync

### ISSUE THREAD

**Issue by MdmrBerlin** [dotnet-websharper/materialui#2]
All examples has an error "Cannot read property 'MuiThemeProvider' of undefined" also here http://try-test.websharper.io/snippet/sandorr/00002U

Start with React.Make Login_ui.Main result in an TypeError: Cannot read property 'Grid' of undefined
Type  _materialui is undefined.

There are missing files?

**Comment by granicz** [comment]
On a quick look, the extension defines the main JS resource file ([here](https://github.com/dotnet-websharper/materialui/blob/master/WebSharper.MaterialUI/Resources.fs#L28)) as

```
https://unpkg.com/@material-ui/core/umd/material-ui.development.js
```

This file is most certainly not the correct one as it's missing the version to which the binding was implemented. The reference as it stands yields the latest version, which indeed is missing `_materialui`, and thus it will fail runtime :(

There are two paths from here: either updating the binding to match the latest JS resource, or pinning the above dependency to the version that works. As a quick fix, I would prefer the latter - but can you help tracking down what that version could be?

**Comment by MdmrBerlin** [comment]
Unfortunately, I have no idea which is the right version.
Does not it make sense to deliver the corresponding version instead of a changing dependency?

**Comment by granicz** [comment]
You mean why not update the binding to match the latest? Referencing the older historical file is quick and makes things work for now, but updating the binding needs a full manual sweep, and that's quite an effort looking at the library. Anyone up for that? If you are, feel free to submit a PR for it. In the meantime, we'll try to hunt down the version number that the current version was implemented against.

**Comment by MdmrBerlin** [comment]
inherit Resources.BaseResource("https://unpkg.com/@material-ui/core@3.9.3/umd/material-ui.production.min.js")

The last working version is this one.
However, a little older.

It would be better to move the include into the index.html, then everyone can choose whether production or development / CDN or local would like. Or an interface / enumerator?

**Comment by granicz** [comment]
Awesome, thanks! I believe @Jand42 did some quick checking and found that the original bindings were made for a pre-1.0 release (tracing back from the fact that they were committed late 2015), but it can easily happen that this version is still a proper subset of 3.9.3.

Either way, you can also reference/change the source of the dependency by setting the FQN of the resource type in `web.config` - as described in the "Resource URL overrides" section of [this documentation page](https://developers.websharper.com/docs/v4.x/fs/runtime-variables).

**Comment by Jand42** [comment]
Bindings have been updated by @Tarmil since the original release, at the release of version 3.0.0, so I think 3.0.3 is safe to use, no breaking changes there only bug fixes. I am testing fixing the link to that one now.

**Comment by Jand42** [comment]
@MdmrBerlin Version 3.0.3 works well with React 16, currently publishing to nuget and to live version of Try.WS (should be available in a couple minutes)
http://try.websharper.com/snippet/sandorr/00002U
I recommend to use the live site, try-test.websharper.io is used for testing new releases, and its database is a clone of the live site that might get wiped.
Thanks for the report!
